################################################################################
# Bedrock Security Control - FMI-07 Knowledge Bases KMS
#
# This unified stack contains all resources for the FMI-07 control:
# - Check Lambda function and IAM role
# - Remediation Lambda function and IAM role
# - Config rule and remediation configuration
# - SSM automation document and role
################################################################################

Parameters:
  TargetOuId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/TargetOuId
    Description: Organization Unit ID where the SCP should be applied
    
  NotificationTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/NotificationTopicArn
    Description: General notification topic ARN
    
  RemediationRetryAttempts:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/RemediationRetryAttempts
    Description: Number of retry attempts for remediation
    
  ConfigRuleFrequency:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/ConfigRuleFrequency
    Description: Frequency for Config rule evaluations
    
  EnableAutoRemediation:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/EnableAutoRemediation
    Description: Enable automatic remediation for Config rules
    
  LambdaCodePrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/LambdaCodePrefix
    Description: Prefix for Lambda code files in S3 bucket
    
  RemediationRetrySeconds:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/RemediationRetrySeconds
    Description: Seconds to wait between remediation retries
    
  TemplatesBucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/TemplatesBucketName
    Description: S3 bucket name for CloudFormation templates
    
  GuardrailChangeNotificationTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/GuardrailChangeNotificationTopicArn
    Description: SNS topic ARN for receiving guardrail change notifications

    
  SecurityGroupIds:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/SecurityGroupIds
    Description: List of Security Group IDs for Lambda functions (leave empty to disable VPC)
    
  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/VpcId
    Description: VPC ID for Lambda functions (leave empty to disable VPC)
    
  PrivateSubnetIds:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/PrivateSubnetIds
    Description: List of private subnet IDs for Lambda functions (leave empty to disable VPC)
    
  KmsKeyId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/fmi-07/KmsKeyId
    Description: KMS key ID for knowledge base encryption
    
  RequiredKmsKeyIds:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/fmi-07/RequiredKmsKeyIds
    Description: Comma-separated list of required KMS key IDs for knowledge base encryption
    

Conditions:
  HasKmsKeyId: !Not [!Equals [!Ref KmsKeyId, "null"]]
  UseVPC: !Not [!Equals [!Ref VpcId, "null"]]

Resources:
  # =========================================================================
  # Check Lambda Function and Role
  # =========================================================================
  BedrockKnowledgeBasesKmsCheckFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "BedrockKnowledgeBasesKmsCheckFunctionRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !If 
          - UseVPC
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: BedrockKnowledgeBasesKmsCheckAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:ListKnowledgeBases'
                  - 'bedrock:GetKnowledgeBase'
                  - 'bedrock:ListDataSources'
                  - 'bedrock:GetDataSource'
                Resource: '*'
        - PolicyName: ConfigRulesAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'config:PutEvaluations'
                Resource: "*"

  BedrockKnowledgeBasesKmsCheckFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "fmi07-KnowledgeBasesKmsCheck"
      Handler: lambda-function.handler
      Role: !GetAtt BedrockKnowledgeBasesKmsCheckFunctionRole.Arn
      Runtime: python3.9
      Timeout: 60
      ReservedConcurrentExecutions: 10
      VpcConfig: !If
        - UseVPC
        - SecurityGroupIds: !Split [",", !Ref SecurityGroupIds]
          SubnetIds: !Split [",", !Ref PrivateSubnetIds]
        - !Ref AWS::NoValue
      Code:
        S3Bucket: !Ref TemplatesBucketName
        S3Key: !Sub "${LambdaCodePrefix}/fmi-07-knowledge-bases-kms-check.zip"

  # =========================================================================
  # Remediation Lambda Function and Role
  # =========================================================================
  BedrockKnowledgeBasesKmsRemediationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "BedrockKnowledgeBasesKmsRemediationFunctionRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
               - ssm.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !If 
          - UseVPC
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Policies:
        - PolicyName: BedrockKnowledgeBasesKmsRemediationAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:ListKnowledgeBases'
                  - 'bedrock:GetKnowledgeBase'
                  - 'bedrock:ListDataSources'
                  - 'bedrock:GetDataSource'
                  - 'bedrock:UpdateDataSource'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'kms:DescribeKey'
                Resource: !If [HasKmsKeyId, !Sub "arn:aws:kms:*:*:key/${KmsKeyId}", '*']
              - Effect: Allow
                Action:
                  - 'sts:GetCallerIdentity'
                Resource: '*'

  BedrockKnowledgeBasesKmsRemediationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "fmi07-KnowledgeBasesKmsRemediation"
      Handler: remediation-lambda-function.handler
      Role: !GetAtt BedrockKnowledgeBasesKmsRemediationFunctionRole.Arn
      Runtime: python3.9
      Timeout: 60
      ReservedConcurrentExecutions: 5
      VpcConfig: !If
        - UseVPC
        - SecurityGroupIds: !Split [",", !Ref SecurityGroupIds]
          SubnetIds: !Split [",", !Ref PrivateSubnetIds]
        - !Ref AWS::NoValue
      Code:
        S3Bucket: !Ref TemplatesBucketName
        S3Key: !Sub "${LambdaCodePrefix}/fmi-07-knowledge-bases-kms-remediation.zip"

  # =========================================================================
  # SSM Automation Role for Remediation
  # =========================================================================
  RemediationAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: "Role for SSM Automation to invoke remediation Lambda"
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt BedrockKnowledgeBasesKmsRemediationFunction.Arn
              - Effect: Allow
                Action:
                  - bedrock:ListKnowledgeBases
                Resource: "*"

  # =========================================================================
  # SSM Automation Document for Remediation
  # =========================================================================
  BedrockKnowledgeBasesKmsRemediationDocument:
    Type: AWS::SSM::Document
    Properties:
      Name: !Sub "BedrockKnowledgeBasesKmsRemediation"
      DocumentType: Automation
      DocumentFormat: YAML
      Content:
        schemaVersion: '0.3'
        description: Reports on Amazon Bedrock knowledge base resource without proper KMS encryption
        assumeRole: !GetAtt RemediationAutomationRole.Arn
        parameters:
          AutomationAssumeRole:
                type: String
                description: The ARN of the role that allows Automation to perform the actions on your behalf
                default: !GetAtt RemediationAutomationRole.Arn
          ResourceId:
                type: String
                description: The ID of the knowledge base resource to remediate
          KmsKeyId:
                type: String
                description: KMS key ID to use for encryption
                default: !Ref KmsKeyId
        mainSteps:
          - name: CheckBedrockKnowledgeBaseKmsEncryption
            action: aws:invokeLambdaFunction
            timeoutSeconds: 120
            maxAttempts: !Ref RemediationRetryAttempts
            onFailure: Abort
            inputs:
              FunctionName: !Ref BedrockKnowledgeBasesKmsRemediationFunction
              Payload: !Sub |
                {
                  "resourceId": "{{ResourceId}}",
                  "kmsKeyId": "{{KmsKeyId}}"
                }
            outputs:
              - Name: Response
                Selector: $.Payload
                Type: String

  # =========================================================================
  # Lambda Permission for Config Rule
  # =========================================================================
  FMI07Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BedrockKnowledgeBasesKmsCheckFunction
      Action: lambda:InvokeFunction
      Principal: config.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  # =========================================================================
  # Config Rule
  # =========================================================================
  FMI07Check:
    Type: AWS::Config::ConfigRule
    DependsOn: FMI07Permission
    Properties:
      ConfigRuleName: !Sub "fmi-07-knowledge-bases-kms"
      Description: "Checks if KMS encryption is configured for individual Bedrock knowledge base resources - Control ID: FMI-07"
      InputParameters: !Sub |
        {
          "requiredKmsKeyIds": "${RequiredKmsKeyIds}"
        }
      Scope:
        ComplianceResourceTypes: 
          - "AWS::Bedrock::KnowledgeBase"
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
          - EventSource: aws.config
            MessageType: OversizedConfigurationItemChangeNotification
        SourceIdentifier: !GetAtt BedrockKnowledgeBasesKmsCheckFunction.Arn

  # =========================================================================
  # Remediation Configuration
  # =========================================================================
  FMI07Remediation:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: !Ref FMI07Check
      TargetId: !Ref BedrockKnowledgeBasesKmsRemediationDocument
      TargetType: SSM_DOCUMENT
      Automatic: !Ref EnableAutoRemediation
      MaximumAutomaticAttempts: !Ref RemediationRetryAttempts
      RetryAttemptSeconds: !Ref RemediationRetrySeconds
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt RemediationAutomationRole.Arn
        ResourceId:
          ResourceValue:
            Value: RESOURCE_ID
        KmsKeyId:
          StaticValue:
            Values:
              - !Ref KmsKeyId

Outputs:
  CheckFunctionArn:
    Description: ARN of the Bedrock Knowledge Bases KMS Check Lambda Function
    Value: !GetAtt BedrockKnowledgeBasesKmsCheckFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CheckFunctionArn'
      
  RemediationFunctionArn:
    Description: ARN of the Bedrock Knowledge Bases KMS Remediation Lambda Function
    Value: !GetAtt BedrockKnowledgeBasesKmsRemediationFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RemediationFunctionArn'
      
  RemediationDocumentName:
    Description: Name of the SSM Automation Document for Knowledge Bases KMS Remediation
    Value: !Ref BedrockKnowledgeBasesKmsRemediationDocument
    Export:
      Name: !Sub '${AWS::StackName}-RemediationDocumentName'
      
  RemediationAutomationRoleArn:
    Description: ARN of the Remediation Automation Role for Knowledge Bases KMS
    Value: !GetAtt RemediationAutomationRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RemediationAutomationRoleArn'
      
  ConfigRuleName:
    Description: Name of the Config Rule for Knowledge Bases KMS
    Value: !Ref FMI07Check
    Export:
      Name: !Sub '${AWS::StackName}-ConfigRuleName'