################################################################################
# Bedrock Security Control - FMI-16 Guardrail Automated Reasoning Policy
#
# This unified stack contains all resources for the FMI-16 control:
# - Check Lambda function and IAM role
# - Remediation Lambda function and IAM role
# - Config rule and remediation configuration
# - SSM automation document and role
################################################################################

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bedrock Security Control - FMI-16 Guardrail Automated Reasoning Policy'

Parameters:
  TemplatesBucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/TemplatesBucketName
    Description: "S3 bucket name for CloudFormation templates"
    
  RemediationRetryAttempts:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/RemediationRetryAttempts
    Description: "Number of retry attempts for remediation"
    
  LambdaCodePrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/LambdaCodePrefix
    Description: "Prefix for Lambda code files in S3 bucket"
    
  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/VpcId
    Description: "VPC ID for Lambda functions (leave empty to disable VPC)"
    
  SecurityGroupIds:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/SecurityGroupIds
    Description: "List of Security Group IDs for Lambda functions (leave empty to disable VPC)"
    
  ConfigRuleFrequency:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/ConfigRuleFrequency
    Description: "Frequency for Config rule evaluations"
    
  RemediationRetrySeconds:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/RemediationRetrySeconds
    Description: "Seconds to wait between remediation retries"
    
  PrivateSubnetIds:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/PrivateSubnetIds
    Description: "List of private subnet IDs for Lambda functions (leave empty to disable VPC)"
    
  EnableAutoRemediation:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/global/EnableAutoRemediation
    Description: "Enable automatic remediation for Config rules"

  # Control-specific parameters
  GuardrailName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/fmi-16/GuardrailName
    Description: 'Optional specific guardrail name to validate'
  AutomatedReasoningPolicies:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/fmi-16/AutomatedReasoningPolicies
    Description: 'Comma-separated list of automated reasoning policy ARNs or IDs'
  MinConfidenceThreshold:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/fmi-16/MinConfidenceThreshold
    Description: 'Minimum confidence threshold for automated reasoning (0.0-1.0)'
  RequiredTags:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /bedrock-configrules/fmi-16/RequiredTags
    Description: 'Optional required tags in key=value,key2=value2 format'

Conditions:
  UseVPC: !Not [!Equals [!Ref VpcId, "null"]]

Resources:
  # =========================================================================
  # Check Lambda Function and Role
  # =========================================================================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "fmi-16-guardrail-automated-reasoning-check-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !If 
          - UseVPC
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: BedrockGuardrailAutomatedReasoningCheckPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - config:PutEvaluations
                Resource: '*'
              - Effect: Allow
                Action:
                  - bedrock:ListGuardrails
                  - bedrock:GetGuardrail
                  - bedrock:ListTagsForResource
                  - bedrock:GetGuardrailVersion
                Resource: '*'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "fmi16-GuardrailAutomatedReasoningCheck"
      Description: "FMI-16: Checks if Bedrock guardrails have proper automated reasoning policy configuration"
      Runtime: python3.9
      Handler: lambda-function.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      MemorySize: 256
      ReservedConcurrentExecutions: 10
      VpcConfig: !If
        - UseVPC
        - SecurityGroupIds: !Split [",", !Ref SecurityGroupIds]
          SubnetIds: !Split [",", !Ref PrivateSubnetIds]
        - !Ref AWS::NoValue
      Code:
        S3Bucket: !Ref TemplatesBucketName
        S3Key: !Sub "${LambdaCodePrefix}/fmi-16-guardrail-automated-reasoning-check.zip"

  # =========================================================================
  # Remediation Lambda Function and Role
  # =========================================================================
  RemediationLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "fmi-16-guardrail-automated-reasoning-remed-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
               - ssm.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !If 
          - UseVPC
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Policies:
        - PolicyName: BedrockGuardrailAutomatedReasoningRemediationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:ListGuardrails
                  - bedrock:GetGuardrail
                  - bedrock:CreateGuardrail
                  - bedrock:UpdateGuardrail
                  - bedrock:CreateAutomatedReasoningPolicy
                  - bedrock:ListTagsForResource
                  - bedrock:TagResource
                  - bedrock:UntagResource
                Resource: '*'

  RemediationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "fmi16-GuardrailAutomatedReasoningRemediation"
      Description: "FMI-16: Creates or updates Bedrock guardrails with proper automated reasoning policy configuration"
      Runtime: python3.9
      Handler: remediation-lambda-function.handler
      Role: !GetAtt RemediationLambdaExecutionRole.Arn
      Timeout: 900
      MemorySize: 512
      ReservedConcurrentExecutions: 5
      VpcConfig: !If
        - UseVPC
        - SecurityGroupIds: !Split [",", !Ref SecurityGroupIds]
          SubnetIds: !Split [",", !Ref PrivateSubnetIds]
        - !Ref AWS::NoValue
      Code:
        S3Bucket: !Ref TemplatesBucketName
        S3Key: !Sub "${LambdaCodePrefix}/fmi-16-guardrail-automated-reasoning-remediation.zip"

  # =========================================================================
  # SSM Automation Role for Remediation
  # =========================================================================
  AutomationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "fmi-16-guardrail-automated-reasoning-auto-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: "Role for SSM Automation to invoke remediation Lambda"
      Policies:
        - PolicyName: AutomationExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt RemediationLambdaFunction.Arn

  # =========================================================================
  # SSM Automation Document for Remediation
  # =========================================================================
  RemediationDocument:
    Type: AWS::SSM::Document
    Properties:
      Name: !Sub "fmi-16-bedrock-guardrail-automated-reasoning-remediation"
      DocumentType: Automation
      DocumentFormat: YAML
      Content:
        schemaVersion: '0.3'
        description: 'FMI-16: Remediation document for creating/updating Bedrock guardrail automated reasoning policy'
        assumeRole: !GetAtt AutomationRole.Arn
        parameters:
          AutomationAssumeRole:
            type: String
            description: The ARN of the role that allows Automation to perform the actions on your behalf
            default: !GetAtt AutomationRole.Arn
          ResourceId:
            type: String
            description: Account ID for account-level remediation
          GuardrailName:
            type: String
            description: Optional specific guardrail name
            default: !Ref GuardrailName
          AutomatedReasoningPolicies:
            type: String
            description: Comma-separated list of automated reasoning policy ARNs or IDs (REQUIRED for remediation)
            default: !Ref AutomatedReasoningPolicies
          MinConfidenceThreshold:
            type: String
            description: Minimum confidence threshold for automated reasoning
            default: !Ref MinConfidenceThreshold
          RequiredTags:
            type: String
            description: Required tags in key=value format
            default: !Ref RequiredTags
        mainSteps:
          - name: InvokeLambdaFunction
            action: 'aws:invokeLambdaFunction'
            description: Invoke Lambda function to create/update guardrail automated reasoning policy
            timeoutSeconds: 900
            maxAttempts: !Ref RemediationRetryAttempts
            onFailure: Abort
            inputs:
              FunctionName: !Ref RemediationLambdaFunction
              Payload: !Sub |
                {
                  "configRuleParameters": {
                    "GuardrailName": "{{GuardrailName}}",
                    "AutomatedReasoningPolicies": "{{AutomatedReasoningPolicies}}",
                    "MinConfidenceThreshold": "{{MinConfidenceThreshold}}",
                    "RequiredTags": "{{RequiredTags}}"
                  },
                  "accountId": "${AWS::AccountId}"
                }
            outputs:
              - Name: Response
                Selector: $.Payload
                Type: String

  # =========================================================================
  # Lambda Permission for Config Rule
  # =========================================================================
  GuardrailAutomatedReasoningPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: config.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  # =========================================================================
  # Config Rule
  # =========================================================================
  GuardrailAutomatedReasoningCheck:
    Type: AWS::Config::ConfigRule
    DependsOn: GuardrailAutomatedReasoningPermission
    Properties:
      ConfigRuleName: !Sub "fmi-16-guardrail-automated-reasoning"
      Description: "Checks if Bedrock guardrails have proper automated reasoning policy configuration at the account level. - Control ID: FMI-16"
      MaximumExecutionFrequency: !Ref ConfigRuleFrequency
      InputParameters: !Sub |
        {
          "GuardrailName": "${GuardrailName}",
          "AutomatedReasoningPolicies": "${AutomatedReasoningPolicies}",
          "MinConfidenceThreshold": "${MinConfidenceThreshold}",
          "RequiredTags": "${RequiredTags}"
        }
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - EventSource: aws.config
            MessageType: ScheduledNotification
            MaximumExecutionFrequency: !Ref ConfigRuleFrequency
        SourceIdentifier: !GetAtt LambdaFunction.Arn

  # =========================================================================
  # Remediation Configuration
  # =========================================================================
  GuardrailAutomatedReasoningRemediation:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: !Ref GuardrailAutomatedReasoningCheck
      TargetId: !Ref RemediationDocument
      TargetType: SSM_DOCUMENT
      Automatic: !Ref EnableAutoRemediation
      MaximumAutomaticAttempts: !Ref RemediationRetryAttempts
      RetryAttemptSeconds: !Ref RemediationRetrySeconds
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt AutomationRole.Arn
        ResourceId:
          ResourceValue:
            Value: RESOURCE_ID
        GuardrailName:
          StaticValue:
            Values:
              - !Ref GuardrailName
        AutomatedReasoningPolicies:
          StaticValue:
            Values:
              - !Ref AutomatedReasoningPolicies
        MinConfidenceThreshold:
          StaticValue:
            Values:
              - !Ref MinConfidenceThreshold
        RequiredTags:
          StaticValue:
            Values:
              - !Ref RequiredTags

Outputs:
  CheckFunctionArn:
    Description: ARN of the Bedrock Guardrail Automated Reasoning Check Lambda Function
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CheckFunctionArn'
      
  RemediationFunctionArn:
    Description: ARN of the Bedrock Guardrail Automated Reasoning Remediation Lambda Function
    Value: !GetAtt RemediationLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RemediationFunctionArn'
      
  RemediationDocumentName:
    Description: Name of the SSM Automation Document for Guardrail Automated Reasoning Remediation
    Value: !Ref RemediationDocument
    Export:
      Name: !Sub '${AWS::StackName}-RemediationDocumentName'
      
  RemediationAutomationRoleArn:
    Description: ARN of the Remediation Automation Role for Guardrail Automated Reasoning
    Value: !GetAtt AutomationRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RemediationAutomationRoleArn'
      
  ConfigRuleName:
    Description: Name of the Config Rule for Guardrail Automated Reasoning
    Value: !Ref GuardrailAutomatedReasoningCheck
    Export:
      Name: !Sub '${AWS::StackName}-ConfigRuleName'